repos:
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        args: [--safe, --quiet]
        language_version: python3

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  # - repo: local
  #   hooks:
  #     - id: pylint
  #       name: pylint
  #       entry: python
  #       language: system
  #       types: [python]
  #       args:
  #         [
  #           "-m",
  #           "pylint",
  #           "-rn", # Only display messages
  #           "-sn", # Don't display the score
  #           "--rcfile=.pylintrc"
  #           # "--load-plugins=pylint.extensions.docparams", # Load an extension
  #         ]

  # - repo: https://github.com/PyCQA/flake8
  #   rev: 4.0.1
  #   hooks:
  #     - id: flake8
  #       exclude: docs
  #       language_version: python3
